language: php

php:
  - 5.6
  - hhvm

sudo: required

before_install:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction


script:
- touch vendor/laravel/laravel/storage/database.sqlite
- yes | cp tests/Stub_User.php vendor/laravel/laravel/app/User.php
- cd vendor/laravel/laravel
- composer install --dev --prefer-source --no-interaction
- php artisan vendor:publish --provider="Hootlex\Friendships\FriendshipsServiceProvider" && php artisan migrate
- cd -
- vendor/bin/phpunit tests